== Embedding CRaSH

The chapter <<running_crash>> explains how to run CRaSH as a standalone or an embedded service. We will study in this section the technical
aspect of running application and show how CRaSH can be embedded in specific environments.

The root class for reusing CRaSH is the +org.crsh.plugin.PluginLifeCycle+ class. This class is abstract and it cannot
be used directly, instead it should be subclasses for providing specific behavior for running CRaSH. There are several
subclasses using it:

* The standalone bootstrap with the +org.crsh.standalone.Bootstrap+ class : designed for using CRaSH with a real
file system (i.e +java.io.File+). It defines a specific layout for locating resources (libraries, configuration and commands).
* The embedded approaches
** +org.crsh.plugin.WebPluginLifeCycle+ : uses a +javax.servlet.ServletContext+
** +org.crsh.spring.SpringBootstrap+ : embeds CRaSH as a Spring bean
** +org.crsh.spring.SpringWebBootstrap+ : extends the +SpringBootstrap+ and uses the existing +ServletContext+

[[standalone_bootstrap]]
=== Standalone bootstrap

The +org.crsh.standalone.Bootstrap+ class is a generic class that can be used to embed the shell in your Java programs
Its usage is quite straighforward and configurable. The bootstrap is a coarse grained approach and it needs a bit of configuration for running:

* The +baseLoader+ properties is the +java.lang.ClassLoader+ used by CRaSH for loading plugins, resources or command sources (under the
_/crash/commands/_ path. This property is not modifiable and must be provided when the bootstrap is instantiated.
* The +config+ properties provides the contextual properties used by CRaSH configuration such as _crash.vfs.refresh_period_
* The +attributes+ property provides the contextual attributes used by CRaSH available at runtime via the +org.crsh.command.CommandContext+,
it is useful for providing objects to commands in a similar fashion to servlet context attributes
* The +cmdPath+ property is a list of +java.io.File+ scanned by CRaSH for loading additional commands
* The +confPath+ property is a list of +java.io.File+ scanned by CRaSH for loading configuration files

Let's see an example on how to use it

=== Standalone CRaSH

The standalone shell is a Java class configurable and runnable from the command line that is used by the standalone distribution. It is
built upon the <<standalone_bootstrap>>.

[[pluggable_auth]]
== Pluggable authentication

Creating a custom authentication mechanism is done by implementing a CRaSH plugin that provides an implementation of the +AuthenticationPlugin+
interface. Let's study the _simple_ authentication plugin implementation.

The +AuthenticationPlugin+ is the interface to implement in order to integrate CRaSH with an authentication mechanism:

////
[source,java]
----
include::{sourcesdir}/org/crsh/auth/AuthenticationPlugin.java[tags=javadoc;classdef]
----
////

[source,java]
----
include::{sourcesdir}/org/crsh/auth/AuthenticationPlugin.java[lines=24..-1]
----

The integration as a CRaSH plugin mandates to extend the class +CRaSHPlugin+ with the generic type +AuthenticationPlugin+:

////
[source,java]
----
public class SimpleAuthenticationPlugin extends
    CRaSHPlugin<AuthenticationPlugin> implements
    AuthenticationPlugin {

include::{sourcesdir}/org/crsh/auth/SimpleAuthenticationPlugin.java[tags=getName;getImplementation]

  ...

}
----
////

[source,java]
----
public class SimpleAuthenticationPlugin extends
    CRaSHPlugin<AuthenticationPlugin> implements
    AuthenticationPlugin {

include::{sourcesdir}/org/crsh/auth/SimpleAuthenticationPlugin.java[lines=76..78;64..67]

  ...

}
----

* The +getName()+ method returns the _simple_ value that matchs the _crash.auth_ configuration property
* The +getImplementation()+ method returns the object that implements the +AuthenticationPlugin+ class, this method
is implemented from the +CRaSHPlugin+ abstract class, but in our case it
simply returns +this+ because +SimpleAuthenticationPlugin+ is directly the implementation class.

Now let's study how the plugin retrieves the configuration properties +crash.auth.simple.username+ and +crash.auth.simple.password+:

////
[source,java]
----
public class SimpleAuthenticationPlugin extends
    CRaSHPlugin<AuthenticationPlugin> implements
    AuthenticationPlugin {

include::{sourcesdir}/org/crsh/auth/SimpleAuthenticationPlugin.java[tags=SIMPLE_USERNAME;SIMPLE_PASSWORD;createConfigurationCapabilities;init]

  ...

}
----
////

[source,java]
----
public class SimpleAuthenticationPlugin extends
    CRaSHPlugin<AuthenticationPlugin> implements
    AuthenticationPlugin {

include::{sourcesdir}/org/crsh/auth/SimpleAuthenticationPlugin.java[lines=32..46;53..59;69..74]

  ...

}
----

* The +createConfigurationCapabilities()+ method returns the constants +SIMPLE_USERNAME+ and +SIMPLE_PASSWORD+ that defines
the configuration properties that the plugin uses
* The +init()+ method is invoked by CRaSH before the plugin will be used, at this moment, the configuration properties are retrieved
from the plugin context with the method +getContext()+ available in the +CRaSHPlugin+ base class

Finally the plugin needs to provide the +authenticate()+ method that implement the authentication logic:

////
[source,java,indent=0]
----
include::{sourcesdir}/org/crsh/auth/SimpleAuthenticationPlugin.java[tags=authenticate]
----
////

[source,java,indent=0]
----
include::{sourcesdir}/org/crsh/auth/SimpleAuthenticationPlugin.java[lines=80..86]
----

The logic is straightforward with an equality check of the username and password.

Last but not least we must declare our plugin to make it recognized by CRaSH, this is achieved thanks to the +java.util.ServiceLoader+
class. CRaSH uses the +ServiceLoader+ for loading plugins and the loader needs a file to be present in the jar file containing
the class under the name +META-INF/services/org.crsh.plugin.CRaSHPlugin+ containing the class name of the plugin:

----
org.crsh.auth.SimpleAuthenticationPlugin
----

When all of this is done, the plugin and its service loader descriptor must be packaged in a jar file and available on the classpath
of CRaSH.

NOTE: You can learn more about the +java.util.ServiceLoader+ by looking at the online http://docs.oracle.com/javase/6/docs/api/java/util/ServiceLoader.html[javadoc].
