The CRaSH JCR extension allow to connect and interract with Java Content Repository implementations.

== JCR implementations

=== eXo JCR

todo

=== Apache Jackrabbit

CRaSH has been tested with Jackrabbit in the following mode : deployment as a resource accessible via JNDI on JBoss 6.1.0.

== SCP usage

Secure copy can be used to import or export content. The username/password prompted by the SSH server will be used
for authentication against the repository when the import or the export is performed.

=== Export a JCR node

The following command will export the node _/gadgets_ in the repository _portal-system_
of the portal container _portal_:

----
scp -P 2000 root@localhost:portal:portal-system:/production/app:gadgets gadgets.xml
----

The node will be exported as _app_gadgets.xml_.

Note that the portal container name is used for GateIn. If you do omit it, then the root container will be used.

=== Import a JCR node

The following command will reimport the node:

----
scp -P 2000 gadgets.xml root@localhost:portal:portal-system:/production/
----

The exported file format use the JCR system view. You can get more information about that in the JCR specification.

CAUTION: The SCP feature is experimental.
